apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: minio
spec:
  selector:
    app: nginx-np
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-np
  template:
    metadata:
      labels:
        app: nginx-np
    spec:
      containers:
        - name: nginx-np
          image: nginx:latest
          ports:
            - containerPort: 80
