apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  labels:
    type: local-path
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce